### ISSUE TITLE
A possible enhancement......

### ISSUE THREAD

**Issue by geogerar** [AlbertMontserrat/UIPlacePicker#3]
Hello,
First of all I would like to thank you for your excellent tool!
Now, I want to propose a possible enhancement.
Can we have also the current user position on map ( of course we can have it very easy )....AND.....
the PATH between the two points ( current user position and the search position ) as overlay on map?

Thanks again...

George Gerardis

**Comment by AlbertMontserrat** [comment]
It would be fun! But it's not the goal of this control. :)
You can do a fork! ;)
